// Validation of task M1 (MATH_SPEC.md): normalised DLT homography estimation.
import { describe, expect, it } from 'vitest';
import { estimateHomography } from '@student';
import { normalizeHomographyScale } from '../../core/linalg';
import { Rng } from '../../core/rng';
import { makeObject, projectObject } from '../../core/synthetic';
import { LANDMARK_SETS } from '../../core/landmark-sets';
import { H_TRUE, expectValidationError, mapAll, maxTransferError, randomPoints } from './helpers';

describe('M1 estimateHomography', () => {
  it('reproduces exact correspondences generated by a known homography', () => {
    const src = randomPoints(30, new Rng(11));
    const dst = mapAll(H_TRUE, src);
    const h = estimateHomography(src, dst);
    expect(h).toHaveLength(9);
    expect(maxTransferError(h, src, dst)).toBeLessThan(1e-6);
  });

  it('recovers the known homography up to scale', () => {
    const src = randomPoints(20, new Rng(12));
    const h = normalizeHomographyScale(estimateHomography(src, mapAll(H_TRUE, src)));
    const truth = normalizeHomographyScale(H_TRUE);
    h.forEach((v, i) => expect(v).toBeCloseTo(truth[i], 9));
  });

  it('works with the minimal number of correspondences (4)', () => {
    const src = [
      { x: 100, y: 100 },
      { x: 900, y: 120 },
      { x: 880, y: 650 },
      { x: 130, y: 600 },
    ];
    const dst = mapAll(H_TRUE, src);
    expect(maxTransferError(estimateHomography(src, dst), src, dst)).toBeLessThan(1e-6);
  });

  it('does not depend on the order of the correspondences', () => {
    const src = randomPoints(15, new Rng(13));
    const dst = mapAll(H_TRUE, src);
    const perm = src.map((_, i) => i).reverse();
    const h1 = normalizeHomographyScale(estimateHomography(src, dst));
    const h2 = normalizeHomographyScale(estimateHomography(perm.map((i) => src[i]), perm.map((i) => dst[i])));
    h1.forEach((v, i) => expect(v).toBeCloseTo(h2[i], 9));
  });

  it('is accurate for large pixel coordinates (tests normalisation)', () => {
    const rng = new Rng(14);
    const src = randomPoints(25, rng, 4000, 3000).map((p) => ({ x: p.x + 2000, y: p.y + 2000 }));
    const dst = mapAll([0.9, 0.1, 400, -0.1, 1.1, -300, 2e-5, 1e-5, 1], src);
    expect(maxTransferError(estimateHomography(src, dst), src, dst)).toBeLessThan(1e-6);
  });

  it('fits projections of a planar object exactly (pinhole camera, two poses)', () => {
    const plane = makeObject('plane');
    const idx = LANDMARK_SETS.rigid.indices;
    const a = projectObject(plane, { yawDeg: -5, pitchDeg: 3 }, 45);
    const b = projectObject(plane, { yawDeg: 20, pitchDeg: -10, rollDeg: 4, tx: 3 }, 45);
    const src = idx.map((i) => a[i]);
    const dst = idx.map((i) => b[i]);
    expect(maxTransferError(estimateHomography(src, dst), src, dst)).toBeLessThan(1e-6);
  });

  it('cannot fit projections of the 3D face exactly (parallax exists)', () => {
    const face = makeObject('face3d');
    const idx = LANDMARK_SETS.rigid.indices;
    const a = projectObject(face, { yawDeg: 0, pitchDeg: 0 }, 50);
    const b = projectObject(face, { yawDeg: 10, pitchDeg: 0 }, 50);
    const src = idx.map((i) => a[i]);
    const dst = idx.map((i) => b[i]);
    expect(maxTransferError(estimateHomography(src, dst), src, dst)).toBeGreaterThan(1);
  });

  it('rejects fewer than 4 correspondences or mismatched lengths', () => {
    const src = randomPoints(3, new Rng(15));
    expectValidationError(() => estimateHomography(src, mapAll(H_TRUE, src)));
    const src5 = randomPoints(5, new Rng(16));
    expectValidationError(() => estimateHomography(src5, mapAll(H_TRUE, src5).slice(0, 4)));
  });

  it('rejects a degenerate configuration (all points collinear)', () => {
    const src = Array.from({ length: 10 }, (_, i) => ({ x: 100 + 50 * i, y: 200 + 20 * i }));
    expectValidationError(() => estimateHomography(src, mapAll(H_TRUE, src)));
  });

  it('never returns NaN for noisy, well-conditioned input', () => {
    const rng = new Rng(17);
    const src = randomPoints(40, rng);
    const dst = mapAll(H_TRUE, src).map((p) => ({ x: p.x + rng.normal(), y: p.y + rng.normal() }));
    expect(estimateHomography(src, dst).every(Number.isFinite)).toBe(true);
  });
});
